"""
tests/test_intake_pdf.py — Phase 5 Day 2 PDF parser tests.

Born-digital path is exercised with the synthetic_note.pdf fixture
(generated by ReportLab in conftest / Day 2 setup). The vision fallback
path is NOT exercised here — it requires a Claude API call costing money;
that path is covered by a dedicated opt-in smoke test gated on the
PHASE5_LLM_TESTS=1 env flag.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from scripts.manager.intake.pdf_parser import (
    VISION_FALLBACK_THRESHOLD_CHARS,
    PdfExtraction,
    extract_text,
)


FIXTURES = Path(__file__).parent / "fixtures" / "phase5"


@pytest.fixture(scope="module")
def synthetic_pdf_bytes() -> bytes:
    return (FIXTURES / "synthetic_note.pdf").read_bytes()


def test_born_digital_extracts_text(synthetic_pdf_bytes: bytes):
    extr: PdfExtraction = extract_text(synthetic_pdf_bytes)
    assert isinstance(extr, PdfExtraction)
    assert extr.page_count == 1
    assert (
        extr.used_vision is False
    ), "born-digital PDF must not trigger vision fallback"
    # PHI redactor must have substituted hospital references
    assert "Wisconsin Virtual A2" not in extr.text
    # Drug names + dose should survive (they aren't PHI)
    assert "Vigabatrin" in extr.text or "VIGABATRIN" in extr.text.upper()


def test_extraction_redactions_count(synthetic_pdf_bytes: bytes):
    extr = extract_text(synthetic_pdf_bytes)
    # Fixture contains: 'A.J., 8-month-old infant' (already redacted form),
    # 'Wisconsin Virtual A2' (hospital), and 'Dr. Jeanette Heitman'
    # (clinician — only redacted if she is registered in the contacts
    # table with contact_type='clinician'). Either way, hospital alone
    # guarantees >= 1 redaction.
    assert extr.redactions_count >= 1


def test_vision_fallback_threshold_constant_is_documented():
    # Sanity check: the threshold is reachable + sane.
    assert 50 <= VISION_FALLBACK_THRESHOLD_CHARS <= 500


@pytest.mark.skipif(
    os.environ.get("PHASE5_LLM_TESTS", "0") != "1",
    reason="set PHASE5_LLM_TESTS=1 to exercise the Claude vision fallback ($ cost)",
)
def test_vision_fallback_path_smoke(synthetic_pdf_bytes: bytes):
    """Force-feed a near-empty PDF so the vision fallback fires."""
    # Construct a tiny PDF with no extractable text
    from reportlab.pdfgen import canvas
    import io as _io

    buf = _io.BytesIO()
    c = canvas.Canvas(buf, pagesize=(72, 72))
    c.showPage()
    c.save()
    blank = buf.getvalue()
    extr = extract_text(blank)
    # Either vision returned empty (still passes threshold check) or fell back.
    assert isinstance(extr, PdfExtraction)
