#!/usr/bin/env python3
"""Squishy-token cluster verifier for v7_architecture/*.md.

The v7_architecture/ doc set was generated by an AI session that fell into
a token-repetition loop on four Georgian filler words. The project style
guide (v7_architecture/AI_BRAIN.md §7 rule 2 and §11) bans repeating any
of them twice in the same paragraph:

    ცარიელი  (empty)
    ცამეტი   (thirteen — should be written as "13")
    ფარული   (hidden)
    ცდილია   (tries / attempts)

This script flags any line where one of those words appears 3+ times
back-to-back. Exit 0 if zero such lines, exit 1 otherwise. The only file
allowed to mention these words multiple times is AI_BRAIN.md itself,
which DEFINES the rule — that case is META and is whitelisted below.

Run:
    python v7_architecture/foundation_logs/check_squishy.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent  # v7_architecture/
WHITELIST = {"AI_BRAIN.md"}  # the doc that DEFINES the rule

PATTERN = re.compile(
    r"(?:ცარიელი|ცამეტი|ფარული|ცდილია)"
    r"[ \t]+(?:ცარიელი|ცამეტი|ფარული|ცდილია)"
    r"[ \t]+(?:ცარიელი|ცამეტი|ფარული|ცდილია)"
)


def main() -> int:
    findings: list[tuple[Path, int, str]] = []
    for md in sorted(ROOT.rglob("*.md")):
        if md.name in WHITELIST:
            continue
        if "foundation_logs" in md.parts:
            continue
        try:
            text = md.read_text(encoding="utf-8")
        except Exception as exc:
            print(f"read fail: {md.relative_to(ROOT)}: {exc}", file=sys.stderr)
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if PATTERN.search(line):
                findings.append((md.relative_to(ROOT), lineno, line.strip()))

    print(f"Scanned: {sum(1 for _ in ROOT.rglob('*.md'))} files under v7_architecture/")
    print(f"Whitelisted (META): {sorted(WHITELIST)}")
    print(f"3+ back-to-back squishy clusters found: {len(findings)}")
    if findings:
        for path, lineno, snippet in findings:
            preview = snippet if len(snippet) <= 120 else snippet[:117] + "..."
            print(f"  {path}:{lineno}: {preview}")
        return 1
    print("PASS — no squishy clusters")
    return 0


if __name__ == "__main__":
    sys.exit(main())
